channels:
  - defaults
  - pytorch
dependencies:
  - pip
  - jupyter
  - scikit-learn
  - scikit-image
  - pytorch
  - matplotlib
  - pillow
  - imageio
  - pip:
     - transformers
     - timm
     - selenium
     - webdriver_manager
     - git+git@github.com:see-insight/see-segment.git
